SELECT H.HACKER_ID, H.NAME, T.TOTAL_SCORE
FROM (
      SELECT HACKER_ID, SUM(MAX_SCORE) AS TOTAL_SCORE
      FROM (
            SELECT HACKER_ID, MAX(SCORE) AS MAX_SCORE
            FROM SUBMISSIONS
            GROUP BY HACKER_ID, CHALLENGE_ID
          ) T1
      GROUP BY HACKER_ID
    ) T, HACKERS H
WHERE H.HACKER_ID = T.HACKER_ID AND TOTAL_SCORE <> 0
ORDER BY TOTAL_SCORE DESC, H.HACKER_ID ASC