SELECT W.ID, P.AGE, W.COINS_NEEDED, W.POWER FROM WANDS W, WANDS_PROPERTY P
WHERE W.CODE = P.CODE AND P.IS_EVIL = 0
AND W.COINS_NEEDED = (
                      SELECT MIN(W1.COINS_NEEDED) FROM WANDS W1, WANDS_PROPERTY P1
                      WHERE W1.CODE = P1.CODE AND P.AGE = P1.AGE
                      AND W.POWER = W1.POWER
                    )
ORDER BY W.POWER DESC, AGE DESC