(SELECT F1.X, F1.Y FROM FUNCTIONS AS F1 
WHERE F1.X = F1.Y GROUP BY F1.X, F1.Y HAVING COUNT(*) > 1)
UNION
(SELECT F1.X, F1.Y FROM FUNCTIONS AS F1
WHERE EXISTS(SELECT X, Y FROM FUNCTIONS WHERE F1.X = Y AND F1.Y = X AND F1.X < X))
ORDER BY X